
import turtle

hamza_turtle = turtle.Turtle()
hamza_turtle.shape("turtle")
hamza_turtle.color("green")
hamza_turtle.fillcolor("green")
hamza_turtle.pencolor("green")
hamza_turtle.ht()

##hamza_turtle.begin_fill()
##for i in range(4):
##    hamza_turtle.fd(90)
##    hamza_turtle.lt(90)
##hamza_turtle.end_fill()

##hamza_turtle.pu()
##hamza_turtle.goto(-500, 0)
##hamza_turtle.pd()
##for i in range(40):
##    hamza_turtle.fd(20)
##    hamza_turtle.pu()
##    hamza_turtle.fd(20)
##    hamza_turtle.pd()

hamza_turtle.pu()
hamza_turtle.fd(100)
hamza_turtle.pd()
hamza_turtle.rt(90)
hamza_turtle.pencolor("yellow")
hamza_turtle.pensize(3)
hamza_turtle.fd(120)
hamza_turtle.rt(90)
hamza_turtle.fd(300)
hamza_turtle.rt(90)
hamza_turtle.fd(360)
hamza_turtle.pencolor("red")
hamza_turtle.rt(45)
hamza_turtle.fd(200)
hamza_turtle.rt(95)
hamza_turtle.fd(200)
hamza_turtle.pencolor("yellow")
hamza_turtle.rt(40)
hamza_turtle.fd(228)
hamza_turtle.lt(90)
hamza_turtle.fd(30)
hamza_turtle.pu()
hamza_turtle.goto(-10, -120)
hamza_turtle.pd()
hamza_turtle.lt(90)
hamza_turtle.fd(150)
hamza_turtle.lt(90)
hamza_turtle.fd(100)
hamza_turtle.lt(90)
hamza_turtle.fd(150)
hamza_turtle.lt(90)
hamza_turtle.fd(100)
hamza_turtle.st()
hamza_turtle.shape("circle")
hamza_turtle.pencolor("green")
hamza_turtle.pu()
hamza_turtle.goto(-25, -45)
